export default {
  'GET /server/fir_api/firs': {
    firs: [
      { firNo: 'KSP-2026-0142', district: 'Bangalore Urban', dateRegistered: '2026-03-15', complainant: 'Rajesh Kumar', crimeType: 'Robbery', status: 'Under Investigation', io: 'PI Dharmendra' },
      { firNo: 'KSP-2026-0089', district: 'Bangalore Urban', dateRegistered: '2026-02-28', complainant: 'Suresh Reddy', crimeType: 'Burglary', status: 'Under Investigation', io: 'PI Maruti' },
      { firNo: 'KSP-2026-0201', district: 'Mysuru', dateRegistered: '2026-01-10', complainant: 'Venkatesh Gowda', crimeType: 'Assault', status: 'Case Closed', io: 'PI Anjumala' },
      { firNo: 'KSP-2026-0156', district: 'Mangaluru', dateRegistered: '2026-04-01', complainant: 'Nadeem Pasha', crimeType: 'Theft', status: 'Under Investigation', io: 'SI Ramesh' },
      { firNo: 'KSP-2026-0234', district: 'Bangalore Urban', dateRegistered: '2026-03-20', complainant: 'Arun Nair', crimeType: 'Fraud', status: 'Under Investigation', io: 'PI Dharmendra' },
      { firNo: 'KSP-2026-0301', district: 'Bangalore Urban', dateRegistered: '2026-05-10', complainant: 'Ajay Rao', crimeType: 'Robbery', status: 'Under Investigation', io: 'SI Patel' },
      { firNo: 'KSP-2026-0267', district: 'Bangalore Urban', dateRegistered: '2026-05-20', complainant: 'Imran Khan', crimeType: 'Burglary', status: 'Under Investigation', io: 'PI Maruti' },
      { firNo: 'KSP-2026-0333', district: 'Shivamogga', dateRegistered: '2026-06-01', complainant: 'Deepa Shetty', crimeType: 'Assault', status: 'Under Investigation', io: 'SI Rao' },
    ],
    total: 8,
  },
  'GET /server/fir_api/fir/142': {
    firNo: 'KSP-2026-0142',
    district: 'Bangalore Urban',
    unitName: 'Brigade Road PS',
    dateRegistered: '2026-03-15',
    complainant: 'Rajesh Kumar',
    crimeType: 'Robbery',
    crimeHead: 'ROBBERY',
    status: 'Under Investigation',
    io: 'PI Dharmendra',
    actSection: 'BNS 304, 309',
    placeOfOffence: 'SH-9 junction, Brigade Road corridor',
    latitude: '12.9762',
    longitude: '77.6033',
    narrative: 'On 2026-03-15 at approximately 8:30 PM, a robbery was reported near the SH-9 junction. Two persons used a sharp object to demand valuables and left on a two-wheeler.',
    accused: ['Mohan Kumar', 'Kiran Joseph'],
    witnesses: 2,
    filingDeadline: '2026-08-09',
    daysRemaining: 18,
  },
  'GET /server/quickml_predict/predict': {
    districtId: 1,
    predictions: [
      { lat: 12.9762, lng: 77.6033, crimeType: 'theft', probability: 0.78, area: 'Brigade Road' },
      { lat: 12.9698, lng: 77.7499, crimeType: 'burglary', probability: 0.65, area: 'Whitefield' },
      { lat: 12.9279, lng: 77.6271, crimeType: 'robbery', probability: 0.52, area: 'BTM Layout' },
      { lat: 13.0298, lng: 77.5654, crimeType: 'assault', probability: 0.44, area: 'Malleshwaram' },
    ],
    modelVersion: 'QuickML-v3.2',
    confidence: 0.81,
  },
  'GET /server/chargesheet_clock/stats': {
    overdueCount: 3,
    atRiskCount: 4,
    safeCount: 3,
    averageOverdueDays: 38,
    worstCase: { firNo: 'KSP-2026-0201', daysOverdue: 88 },
    cases: [
      { caseId: 1, firNo: 'KSP-2026-0142', crimeType: 'robbery', officer: 'PI Dharmendra', daysSinceRegistration: 129, cpcLimitDays: 147, daysOverdue: 0, daysRemaining: 18, deadlineDate: '2026-08-09', status: 'at_risk' },
      { caseId: 2, firNo: 'KSP-2026-0089', crimeType: 'burglary', officer: 'PI Maruti', daysSinceRegistration: 144, cpcLimitDays: 150, daysOverdue: 0, daysRemaining: 6, deadlineDate: '2026-07-28', status: 'at_risk' },
      { caseId: 3, firNo: 'KSP-2026-0201', crimeType: 'assault', officer: 'PI Anjumala', daysSinceRegistration: 178, cpcLimitDays: 90, daysOverdue: 88, deadlineDate: '2026-04-10', status: 'overdue' },
      { caseId: 4, firNo: 'KSP-2026-0156', crimeType: 'theft', officer: 'SI Ramesh', daysSinceRegistration: 97, cpcLimitDays: 90, daysOverdue: 7, deadlineDate: '2026-06-30', status: 'overdue' },
      { caseId: 5, firNo: 'KSP-2026-0234', crimeType: 'fraud', officer: 'PI Dharmendra', daysSinceRegistration: 109, cpcLimitDays: 90, daysOverdue: 19, deadlineDate: '2026-06-18', status: 'overdue' },
      { caseId: 6, firNo: 'KSP-2026-0301', crimeType: 'robbery', officer: 'SI Patel', daysSinceRegistration: 58, cpcLimitDays: 90, daysOverdue: 0, daysRemaining: 32, deadlineDate: '2026-08-08', status: 'at_risk' },
      { caseId: 7, firNo: 'KSP-2026-0267', crimeType: 'burglary', officer: 'PI Maruti', daysSinceRegistration: 48, cpcLimitDays: 90, daysOverdue: 0, daysRemaining: 42, deadlineDate: '2026-08-18', status: 'at_risk' },
      { caseId: 8, firNo: 'KSP-2026-0333', crimeType: 'assault', officer: 'SI Rao', daysSinceRegistration: 36, cpcLimitDays: 90, daysOverdue: 0, daysRemaining: 54, deadlineDate: '2026-08-30', status: 'safe' },
      { caseId: 9, firNo: 'KSP-2026-0359', crimeType: 'theft', officer: 'PI Anjumala', daysSinceRegistration: 22, cpcLimitDays: 90, daysOverdue: 0, daysRemaining: 68, deadlineDate: '2026-09-13', status: 'safe' },
      { caseId: 10, firNo: 'KSP-2026-0388', crimeType: 'fraud', officer: 'SI Ramesh', daysSinceRegistration: 15, cpcLimitDays: 90, daysOverdue: 0, daysRemaining: 75, deadlineDate: '2026-09-20', status: 'safe' },
    ],
  },
  'GET /server/network_analysis/graph': {
    nodes: [
      { id: 'N1', label: 'Person A', group: 1, size: 12 },
      { id: 'N2', label: 'Person B', group: 1, size: 10 },
      { id: 'N3', label: 'Person C', group: 2, size: 8 },
      { id: 'N4', label: 'Victim 1', group: 3, size: 6 },
      { id: 'N5', label: 'Witness', group: 4, size: 5 },
      { id: 'N6', label: 'Person D', group: 2, size: 9 },
      { id: 'N7', label: 'Recorded contact', group: 4, size: 4 },
      { id: 'N8', label: 'Victim 2', group: 3, size: 5 },
    ],
    links: [
      { source: 'N1', target: 'N2', weight: 5, relation: 'shared-FIR record' },
      { source: 'N1', target: 'N3', weight: 3, relation: 'recorded contact' },
      { source: 'N2', target: 'N6', weight: 4, relation: 'recorded family relation' },
      { source: 'N3', target: 'N6', weight: 2, relation: 'shared-FIR record' },
      { source: 'N1', target: 'N4', weight: 1, relation: 'accused-victim record' },
      { source: 'N3', target: 'N8', weight: 1, relation: 'accused-victim record' },
      { source: 'N5', target: 'N4', weight: 1, relation: 'witness record' },
      { source: 'N6', target: 'N7', weight: 2, relation: 'recorded contact' },
    ],
    communities: 4,
    totalCases: 6,
    metadata: { mode: 'synthetic-demo', humanReviewRequired: true },
  },
  'POST /server/zia_voice/stt': {
    text: 'A robbery took place near Brigade Road junction around 8 PM on March 15th. Two persons on a motorcycle snatched a gold chain and fled towards Shivajinagar.',
  },
  'POST /server/zia_voice/tts': {
    audioUrl: null,
    message: 'TTS not available in offline mode',
  },
  'POST /server/login': {
    __status: 401,
    message: 'Use mock token for offline demo.',
  },
  'GET /server/fir_api/alerts': [
    { id: 1, type: 'DOCUMENTATION', severity: 'high', title: 'FIR KSP-2026-0142 needs CCTV custody documentation', district: 'Bangalore Urban', timestamp: '2026-07-22T08:45:00Z' },
    { id: 2, type: 'HOTSPOT', severity: 'medium', title: 'Brigade Road showing elevated theft activity', district: 'Bangalore Urban', timestamp: '2026-07-06T07:30:00Z' },
    { id: 3, type: 'CASE_READINESS', severity: 'low', title: 'FIR KSP-2026-0234 readiness needs review', district: 'Bengaluru Urban', timestamp: '2026-07-06T06:15:00Z' },
    { id: 4, type: 'FAIRNESS', severity: 'medium', title: 'Recidivism model parity ratio below threshold (0.75)', district: 'All', timestamp: '2026-07-06T05:00:00Z' },
  ],
  'GET /server/case-management/stats': {
    totalCases: 1247,
    activeCases: 483,
    closedCases: 764,
    pendingInCourt: 218,
    clearanceRate: 0.61,
    avgResolutionDays: 47,
    byStage: { investigation: 198, chargesheet: 142, trial: 89, appeal: 54 },
    bySeverity: { petty: 312, misdemeanour: 156, felony: 15 },
  },
  'GET /server/predictive_mode/predict': {
    districtId: 1,
    districtName: 'Bengaluru Urban',
    firCount: 1247,
    method: 'offline-demo',
    generatedAt: '2026-07-22T09:00:00+05:30',
    topCrimes: [['robbery', 145], ['theft', 121], ['burglary', 88]],
    predictions: [
      { crime_type: 'robbery', confidence: 0.78, location: 'Brigade Road corridor', time_window: '18:00-22:00', reasoning: 'Seven-day robbery count is 1.6x the seasonal baseline.' },
      { crime_type: 'theft', confidence: 0.64, location: 'Majestic transit interchange', time_window: '16:00-20:00', reasoning: 'Transit-footfall and recent theft reports exceed the demonstration threshold.' },
      { crime_type: 'burglary', confidence: 0.47, location: 'Indiranagar east beat', time_window: '00:00-04:00', reasoning: 'A small night-time cluster is present.' },
    ],
    limitations: ['Offline demonstration data', 'Signals support patrol planning only'],
  },
  'GET /server/topology_navigator/topology': {
    nodes: [
      { id: 'theft', label: 'Theft', size: 22, fsc: 0.42, crimeCount: 145 },
      { id: 'burglary', label: 'Burglary', size: 18, fsc: 0.55, crimeCount: 98 },
      { id: 'robbery', label: 'Robbery', size: 16, fsc: 0.38, crimeCount: 67 },
      { id: 'assault', label: 'Assault', size: 20, fsc: 0.61, crimeCount: 112 },
      { id: 'murder', label: 'Murder', size: 10, fsc: 0.78, crimeCount: 14 },
      { id: 'sexual', label: 'Sexual Violence', size: 14, fsc: 0.71, crimeCount: 43 },
      { id: 'fraud', label: 'Fraud', size: 17, fsc: 0.49, crimeCount: 89 },
      { id: 'cyber', label: 'Cybercrime', size: 15, fsc: 0.66, crimeCount: 56 },
      { id: 'drugs', label: 'Drug Offenses', size: 19, fsc: 0.58, crimeCount: 78 },
    ],
    edges: [
      { source: 'theft', target: 'burglary', weight: 0.28, width: 2.8 },
      { source: 'theft', target: 'robbery', weight: 0.19, width: 1.9 },
      { source: 'robbery', target: 'assault', weight: 0.25, width: 2.5 },
      { source: 'fraud', target: 'cyber', weight: 0.33, width: 3.3 },
      { source: 'drugs', target: 'assault', weight: 0.16, width: 1.6 },
    ],
    metadata: { totalCrimes: 1247, crimeTypeCount: 12, districtId: 1 },
  },
  'GET /server/accused_at_large/ledger': {
    total: 8,
    abscondingCount: 5,
    entries: [
      { id: 1, name: 'Kiran Joseph', crimeType: 'robbery', firNo: 'KSP-2026-0142', daysAtLarge: 112, status: 'warrant_verification', lastKnownLocation: 'Shivajinagar, Bengaluru', officer: 'PI Dharmendra' },
      { id: 2, name: 'Ravi Shetty', crimeType: 'burglary', firNo: 'KSP-2026-0089', daysAtLarge: 114, status: 'absconding', lastKnownLocation: 'Belgaum', officer: 'PI Maruti' },
      { id: 3, name: 'Venkatesh Gowda', crimeType: 'assault', firNo: 'KSP-2026-0201', daysAtLarge: 156, status: 'absconding', lastKnownLocation: 'Mysuru', officer: 'PI Anjumala' },
      { id: 4, name: 'Nadeem Pasha', crimeType: 'theft', firNo: 'KSP-2026-0156', daysAtLarge: 73, status: 'absconding', lastKnownLocation: 'Mangaluru', officer: 'SI Ramesh' },
      { id: 5, name: 'Arun Nair', crimeType: 'fraud', firNo: 'KSP-2026-0234', daysAtLarge: 93, status: 'absconding', lastKnownLocation: 'Udupi', officer: 'PI Dharmendra' },
    ],
  },
}
